# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Project Management'
copyright = 'Alexandre Bobkov 2025'
author = 'Alexandre Bobkov'
release = 'Fall 2025 (v25.09.05)'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx_simplepdf",
]

templates_path = ['_templates']
include_patterns = ['*.rst', '*.md']
exclude_patterns = []

# The master toctree document.
master_doc = 'index'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
# The name of the default role to use for all documents.
default_role = 'literal'
# The encoding of source files.
source_encoding = 'utf-8-sig'
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
version = 'Fall 2025'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']

# SimplePDF Customization

imgmath_image_format = 'png'
imgmath_dvi_png_args = ['-gamma', '1.5', '-D', '110', '-bg', 'Transparent']
imgmath_use_preview = True

simplepdf_style = 'default'
simplepdf_coverpage = True
simplepdf_toc_depth = 3
simplepdf_title = 'Project Management'
simplepdf_author = 'Alexandre Bobkov'
simplepdf_css = '_static/simplepdf.css'
simplepdf_style = 'green'
simplepdf_file_name = 'F25_360-B70_Project-Management-Handouts.pdf'
simplepdf_vars = {
    #'primary': "#23A3EC",
    'links': '#FF3333',
    'bottom-center-content': '"Project Management"',
    'bottom-right-content': '"Alexandre Bobkov"',
}
